version: 2.1

orbs:
  aws-cli: circleci/aws-cli@5.1.0
  kubernetes: circleci/kubernetes@1.3.1
  node: circleci/node@6.1.0

parameters:
  cluster_name:
    type: string
    default: "staging-eu"

commands:
  cluster_setup:
    steps:
      - aws-cli/setup
      - kubernetes/install-kubectl:
          kubectl-version: v1.30.3
      - run:
          name: Set up cluster context
          command: aws eks update-kubeconfig --name << pipeline.parameters.cluster_name >> --alias << pipeline.parameters.cluster_name >>

jobs:
  fan_out:
    executor: node/default
    steps:
      - run: echo "Building $CIRCLE_BRANCH"

  node_run:
    executor: node/default
    parameters:
      steps:
        type: steps
        default: []
    steps:
      - checkout
      - node/install # install Node.js from .nvmrc
      - node/install-packages:
          include-branch-in-cache-key: false
      - steps: << parameters.steps >>

workflows:
  build:
    jobs:
      - fan_out:
          filters:
            branches:
              only:
                - main

      - be_kind_to_your_colleagues:
          type: approval
          filters:
            branches:
              ignore:
                - main

      - node_run:
          name: commitlint
          filters:
            branches:
              ignore:
                - main
                - /^dependabot-.*$/
          requires:
            - fan_out
            - be_kind_to_your_colleagues
          steps:
            - run: npx commitlint --from $(git merge-base main $CIRCLE_BRANCH) --to HEAD --verbose

      - node_run:
          name: build
          requires:
            - fan_out
            - be_kind_to_your_colleagues
          steps:
            - run: npm run build

      - node_run:
          name: lint
          requires:
            - fan_out
            - be_kind_to_your_colleagues
          steps:
            - run: npm run lint

      - node_run:
          name: test
          requires:
            - fan_out
            - be_kind_to_your_colleagues
          steps:
            - run: npm test -- run --reporter default --reporter junit --outputFile.junit=junit.xml
            - store_test_results:
                path: junit.xml

      - node_run:
          name: e2e
          context:
            - docker-hub-secrets
            - k8s-deploy-to-shared-aspire-20220211
            - aws-region-eu
          requires:
            - build
            - lint
            - test
          steps:
            - cluster_setup
            - run:
                name: Run e2e tests
                environment:
                  DEBUG_DETIK: "true"
                command: |
                  mkdir test-results
                  # dummy directory passed to bats as first to force absolute paths
                  # in JUnit, see https://github.com/bats-core/bats-core/issues/913
                  mkdir dummy
                  circleci tests glob "e2e/*.bats" | circleci tests run --verbose \
                    --command="xargs npm exec -- bats --jobs 4 --no-parallelize-within-files --timing --print-output-on-failure --report-formatter junit --output test-results dummy"
            - store_artifacts:
                path: /tmp/detik
            - store_test_results:
                path: test-results

      - node_run:
          name: semantic-release
          requires:
            - e2e
          steps:
            - run: npm run release
